### ISSUE TITLE
Change our setScore operations for Firestore.increment

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chatbot#46]
# Introduction

As we'll have now multiple `coverbot`s writing into our score database, we need to ensure we increase our node scores atomically, as otherwise if `N` bots write on a given node at the same time, instead of increasing their score by `relay_points * N` points, we'll be doing `relay_points` only.

# Task Description

- Change https://github.com/hoprnet/hopr-chatbot/blob/feature/basodino/src/bots/coverbot/index.ts#L116 to use [Firestore Increment](https://fireship.io/snippets/firestore-increment-tips/) instead. Make sure to use `score.Relayed` constant (seen used [here](https://github.com/hoprnet/hopr-chatbot/blob/feature/basodino/src/bots/coverbot/index.ts#L382)) to select the amount to increase.

**Comment by nionis** [comment]
Closed by #45
