### ISSUE TITLE
Restore and load once the score table from another network

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chatbot#47]
# Introduction

For the round two of basodino, we'll need to copy the `score` "table" from the `basodino` "database" from our Firestore actual database, and restore them with a score of `100`. This process should only run once if the "database" value for the `score` "table" is empty.

# Task Description
- Add in `coverbot/constants.ts` an array of the possible "databases" we can switch/base our scores from. Right now the value is `["basodino","basodino-develop"]`
- Create `COVERBOT_DATABASE_RESTORE_SCORE_FROM` env in our `env.ts`, with possible values being grabbed from `coverbot/constants.ts`
- On load, `coverbot` checks if its `score` "table" is empty AND `COVERBOT_DATABASE_RESTORE_SCORE_FROM` is different from `null`. If so, then it copies the `score` "table" from `COVERBOT_DATABASE_RESTORE_SCORE_FROM`'s value, and iterates over them to make them `100` before updating the new `score` table.
- If a previously loaded `score` "table" exists, then nothing is done.

# Notes
Although implementation is suggested, another alternative is welcomed. The goal is provided in the task subject. Also, the terms "table", "database" and database are used to express the NoSQL nature of our score key-value entry, where:

```
database (firestore)
\_ "database" (network, e.g. basodino)
   \_ "table" (i.e score or state)
```

**Comment by nionis** [comment]
Closed by #49
