### ISSUE TITLE
Store coverbot address alongside a random number for further verification

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chatbot#48]
# Introduction

As part of the new relay schema, `coverbot`s can send other `coverbot`s messages to "ask" them to try and relay a message on the original's `coverbot` behalf. This process can be completed as much as `N` times, and looks something as follows:

![Paper HOPR-IN 7](https://user-images.githubusercontent.com/1128312/98357430-7d1f1580-2025-11eb-8401-ce33682da199.png)

To avoid fake `coverbot`s to trigger calls from nodes that are not HOPR Services AG bots, we'll store the address of the "official" coverbots into our database. We'll then ask coverbot to only listen to relays from messages that come from these registered `coverbot`s.

# Task Description

- On start, store in the "database" inside the "table" `bots` the following key-value entry `{$NODE: $SECRET}` where `$NODE` is the `this.address` of the bot and `$SECRET` is a randomly generated numerical number. This value can be rewritten as many times, as will be read before validating any relay.

# Notes
Upon completing this task, here's what the Firestore database could look like:

```
database
\_ basodino-v2-develop-steven
    \_ score = {...}
    \_ state = {...}
    \_ bots
       \_ { 16Uiu2HAkzz6ciBeuPCJ4mL3BCgbPhW4SyRwn8jd4gv8Q8w3P2Q5W: 939926 }
```

**Comment by nionis** [comment]
Closed by #50

**Comment by SCBuergel** [comment]
@nionis & @jjperezaguinaga can you confirm that the DB is not publicly exposed anymore? Last time the `.json` was publicly available and this could then still be used to spoof a response with a not-so-secret secret.

**Comment by nionis** [comment]
taken care of @SCBuergel thx
