### ISSUE TITLE
Check relayed messages are valid messages from coverbots

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chatbot#51]
# Introduction

Requires #48. The way `coverbot` has been verifying users is by sending a message to itself in the following manner:

`coverbot.send(coverbot, message, [node])`

You can actually see how coverbot sends those messages in https://github.com/hoprnet/hopr-chatbot/blob/feature/basodino/src/bots/coverbot/index.ts#L322. The issue of that approach is that due to the way we encode messages, any node could "pretend" being coverbot. In reality, a closer analysis to the way coverbot is verifying nodes is by decoding the messages and seeing the actual method as follows:

`coverbot.send(coverbot, "$coverbot: verifying $node", [node])`

This means that any node could actually do the following:

`node.send(coverbot, "$coverbot: verifying $node", [])`

which would be picked up in https://github.com/hoprnet/hopr-chatbot/blob/feature/basodino/src/bots/coverbot/index.ts#L406 as "coverbot successfully used $node" for relaying, which in reality would be a node that sent a message with `settings includeRecipient false` with the content "$coverbotAddress: verifying $myOwnNode".

This was a known 🐛 in the bot internally, which was up for grabs during our last session 👀 . As we will be using additional functionality for incoming sessions, we'll be patching that now. From now on, the "listener" of a message for coverbot upon successful relay (i.e. [this line](https://github.com/hoprnet/hopr-chatbot/blob/feature/basodino/src/bots/coverbot/index.ts#L406)) will not only check that the message sent to it "comes from"* a `coverbot` address, but also that the contents have the `$SECRET` created for that particular node.

# Task Description

- Modify https://github.com/hoprnet/hopr-chatbot/blob/feature/basodino/src/bots/coverbot/index.ts#L322 such as it includes the `$SECRET` value create by the coverbot (see #48) and include it as part of the message.
- Modify https://github.com/hoprnet/hopr-chatbot/blob/feature/basodino/src/bots/coverbot/index.ts#L406 such as it checks not only the `message.from` but also that `message.text` includes the $SECRET of _that_ particular coverbot. Since messages can be sent as a request from other coverbot, make sure to read our database bots "table" and compare the contents of $SECRET such as `bots[message.from] === getSecret(message.text)`

# Additional notes

* we marked "comes from" because in reality, HOPR does not sign messages and currently makes no use of certificates to verify a message was sent by `A` or `B`. This is by design, but could be changed in the future and/or implemented on an application layer (as we are currently doing with coverbot with $SECRET, although there are of course better implementations).

**Comment by nionis** [comment]
@jjperezaguinaga please take a look at #52 (which is merged already) and if it's all good close this issue

**Comment by jjperezaguinaga** [comment]
Completed in #52, add a new modification in #44 that allows checking secrets dynamically, so that's enough. Closing and thanks @nionis !
